routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::match(["GET", "POST"], "/register", function(){
    return redirect("/login");
})->name("register");

Route::get('/home', 'HomeController@index')->name('home');

Route::resource("users", "UserController");

Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');

Route::get('/categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');

Route::delete('/categories/{id}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete-permanent');

Route::resource('categories', 'CategoryController');

Route::get('/books/trash', 'BookController@trash')->name('books.trash');

Route::post('/books/{id}/restore', 'BookController@restore')->name('books.restore');

Route::delete('/books/{id}/delete-permanent', 'BookController@deletePermanent')->name('books.delete-permanent');

Route::resource('books', 'BookController');

Route::get('/ajax/categories/search', 'CategoryController@ajaxSearch');


Route::resource('orders', 'OrderController');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use SoftDeletes;

    public function categories(){
        return $this->belongsToMany('App\Category');
        
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $status = $request->get('status');
        $keyword = $request->get('keyword') ? $request->get('keyword') : '';

        if($status){
            $books = \App\Book::with('categories')->where('title', "LIKE", "%$keyword%")->where('status', strtoupper($status))->paginate(10);
        } else {
            $books = \App\Book::with('categories')->where("title", "LIKE", "%$keyword%")->paginate(10);
        }

        return view('books.index', ['books' => $books]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        \Validator::make($request->all(), [
            "title" => "required|min:5|max:200",
            "description" => "required|min:20|max:1000",
            "author" => "required|min:3|max:100",
            "publisher" => "required|min:3|max:200",
            "price" => "required|digits_between:0,10",
            "stock" => "required|digits_between:0,10",
            "cover" => "required|image|mimes:jpeg,png,jpg|max:2048"
        ])->validate();  


        $new_book = new \App\Book;
        $new_book->title = $request->get('title');
        $new_book->description = $request->get('description');
        $new_book->author = $request->get('author');
        $new_book->publisher = $request->get('publisher');
        $new_book->price = $request->get('price');
        $new_book->stock = $request->get('stock');

        $new_book->status = $request->get('save_action');

        $cover = $request->file('cover');

        if($cover){
            $cover_path = $cover->store('book-covers', 'public');

            $new_book->cover = $cover_path;
        }

        $new_book->slug = str_slug($request->get('title'));

        $new_book->created_by = \Auth::user()->id;

        $new_book->save();

        $new_book->categories()->attach($request->get('categories'));

        if($request->get('save_action') == 'PUBLISH'){
            return redirect()
                ->route('books.create')
                ->with('status', 'Book successfully saved and published');
        } else {
            return redirect()
                ->route('books.create')
                ->with('status', 'Book saved as draft');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = \App\Book::findOrFail($id);

        return view('books.edit', ['book' => $book]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $book = \App\Book::findOrFail($id);

        \Validator::make($request->all(), [
            "title" => "required|min:5|max:200",
            "slug" => [
                "required",
                Rule::unique("books")->ignore($book->slug, "slug")
            ],
            "description" => "required|min:20|max:1000",
            "author" => "required|min:3|max:100",
            "publisher" => "required|min:3|max:200",
            "price" => "required|digits_between:0,10",
            "stock" => "required|digits_between:0,10",
            "cover" => "image|mimes:jpeg,png,jpg|max:2048"
        ])->validate();  

        $book->title = $request->get('title');
        $book->slug = $request->get('slug');
        $book->description = $request->get('description');
        $book->author = $request->get('author');
        $book->publisher = $request->get('publisher');
        $book->stock = $request->get('stock');
        $book->price = $request->get('price');

        $new_cover = $request->file('cover');

        if($new_cover){
            if($book->cover && file_exists(storage_path('app/public/' . $book->cover))){
                \Storage::delete('public/'. $book->cover);
            }

            $new_cover_path = $new_cover->store('book-covers', 'public');

            $book->cover = $new_cover_path;
        }

        $book->updated_by = \Auth::user()->id;

        $book->status = $request->get('status');

        $book->save();

        $book->categories()->sync($request->get('categories'));

        return redirect()->route('books.edit', ['id'=>$book->id])->with('status', 'Book successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = \App\Book::findOrFail($id);
        $book->delete();

        return redirect()->route('books.index')->with('status', 'Book moved to trash');
    }

    public function trash(){
        $books = \App\Book::onlyTrashed()->paginate(10);
      
        return view('books.trash', ['books' => $books]);
      }

      public function restore($id){
        $book = \App\Book::withTrashed()->findOrFail($id);
      
        if($book->trashed()){
          $book->restore();
          return redirect()->route('books.trash')->with('status', 'Book successfully restored');
        } else {
          return redirect()->route('books.trash')->with('status', 'Book is not in trash');
        }
      }

      public function deletePermanent($id){
        $book = \App\Book::withTrashed()->findOrFail($id);
      
        if(!$book->trashed()){
          return redirect()->route('books.trash')->with('status', 'Book is not in trash!')->with('status_type', 'alert');
        } else {
          $book->categories()->detach();
          $book->forceDelete();
      
          return redirect()->route('books.trash')->with('status', 'Book permanently deleted!');
        }
      }

}

resources/views/books/create.blade.php
@extends('layouts.global')

@section('title') Create book @endsection

@section('content')
<div class="row">
    <div class="col-md-8">
        @if(session('status'))
        <div class="alert alert-success">
            {{session('status')}}
        </div>
        @endif

        <form action="{{route('books.store')}}" method="POST" enctype="multipart/form-data" class="shadow-sm p-3 bg-white">

            @csrf

            <label for="title">Title</label> <br>
            <input value="{{old('title')}}" type="text" class="form-control {{$errors->first('title') ? "is-invalid" : ""}} "
                name="title" placeholder="Book title">
            <div class="invalid-feedback">
                {{$errors->first('title')}}
            </div>
            <br>

            <label for="cover">Cover</label>
            <input type="file" class="form-control {{$errors->first('cover') ? "is-invalid" : ""}} " name="cover">
            <div class="invalid-feedback">
                {{$errors->first('cover')}}
            </div>
            <br>

            <label for="description">Description</label><br>
            <textarea name="description" id="description" class="form-control {{$errors->first('description') ? "is-invalid" : ""}} "
                placeholder="Give a description about this book">{{old('description')}}</textarea>
            <div class="invalid-feedback">
                {{$errors->first('description')}}
            </div>
            <br>

            <label for="categories">Categories</label><br>
            <select name="categories[]" multiple id="categories" class="form-control"></select>
            <br><br>

            <label for="stock">Stock</label><br>
            <input value="{{old('stock')}}" type="number" class="form-control {{$errors->first('stock') ? "is-invalid" : ""}} "
                id="stock" name="stock" min=0 value=0>
            <div class="invalid-feedback">
                {{$errors->first('stock')}}
            </div>
            <br>

            <label for="author">Author</label><br>
            <input value="{{old('author')}}" type="text" class="form-control {{$errors->first('author') ? "is-invalid" : ""}} "
                name="author" id="author" placeholder="Book author">
            <div class="invalid-feedback">
                {{$errors->first('author')}}
            </div>
            <br>

            <label for="publisher">Publisher</label> <br>
            <input value="{{old('publisher')}}" type="text" class="form-control {{$errors->first('publisher') ? "is-invalid" : ""}} "
                id="publisher" name="publisher" placeholder="Book publisher">
            <div class="invalid-feedback">
                {{$errors->first('publisher')}}
            </div>
            <br>

            <label for="Price">Price</label> <br>
            <input value="{{old('price')}}" type="number" class="form-control {{$errors->first('price') ? "is-invalid" : ""}} "
                name="price" id="price" placeholder="Book price">
            <div class="invalid-feedback">
                {{$errors->first('price')}}
            </div>
            <br>

            <button class="btn btn-primary" name="save_action" value="PUBLISH">Publish</button>
            <button class="btn btn-secondary" name="save_action" value="DRAFT">Save as draft</button>
        </form>
    </div>
</div>
@endsection

@section('footer-scripts')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script>
    $('#categories').select2({
        ajax: {
            url: '/ajax/categories/search',
            processResults: function (data) {
                return {
                    results: data.map(function (item) {
                        return {
                            id: item.id,
                            text: item.name
                        }
                    })
                }
            }
        }
    });
</script>
@endsection

resources/views/books/edit.blade.php
@extends('layouts.global')

@section('title') Edit book @endsection

@section('content')

<div class="row">
    <div class="col-md-8">

        @if(session('status'))
        <div class="alert alert-success">
            {{session('status')}}
        </div>
        @endif

        <form enctype="multipart/form-data" method="POST" action="{{route('books.update', ['id' => $book->id])}}" class="p-3 shadow-sm bg-white">

            @csrf
            <input type="hidden" name="_method" value="PUT">

            <label for="title">Title</label><br>
            <input type="text" class="form-control" value="{{$book->title}}" name="title" placeholder="Book title" />
            <br>

            <label for="cover">Cover</label><br>
            <small class="text-muted">Current cover</small><br>
            @if($book->cover)
            <img src="{{asset('storage/' . $book->cover)}}" width="96px" />
            @endif
            <br><br>
            <input type="file" class="form-control {{$errors->first('cover') ? "is-invalid" : ""}} " name="cover">
            <div class="invalid-feedback">
                {{$errors->first('cover')}}
            </div>
            <small class="text-muted">Kosongkan jika tidak ingin mengubah cover</small>
            <br><br>

            <label for="slug">Slug</label><br>
            <input type="text" class="form-control" value="{{$book->slug}}" name="slug" placeholder="enter-a-slug" />
            <br>

            <label for="description">Description</label> <br>
            <textarea name="description" id="description" class="form-control">{{$book->description}}</textarea>
            <br>

            <label for="categories">Categories</label>
            <select multiple class="form-control" name="categories[]" id="categories"></select>
            <br>
            <br>

            <label for="stock">Stock</label><br>
            <input type="text" class="form-control" placeholder="Stock" id="stock" name="stock" value="{{$book->stock}}">
            <br>

            <label for="author">Author</label>
            <input placeholder="Author" value="{{$book->author}}" type="text" id="author" name="author" class="form-control">
            <br>

            <label for="publisher">Publisher</label><br>
            <input class="form-control" type="text" placeholder="Publisher" name="publisher" id="publisher" value="{{$book->publisher}}">
            <br>

            <label for="price">Price</label><br>
            <input type="text" class="form-control" name="price" placeholder="Price" id="price" value="{{$book->price}}">
            <br>

            <label for="">Status</label>
            <select name="status" id="status" class="form-control">
                <option {{$book->status == 'PUBLISH' ? 'selected' : ''}} value="PUBLISH">PUBLISH</option>
                <option {{$book->status == 'DRAFT' ? 'selected' : ''}} value="DRAFT">DRAFT</option>
            </select>
            <br>

            <button class="btn btn-primary" value="PUBLISH">Update</button>

        </form>
    </div>
</div>

@endsection

@section('footer-scripts')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script>
    $('#categories').select2({
        ajax: {
            url: '/ajax/categories/search',
            processResults: function (data) {
                return {
                    results: data.map(function (item) {
                        return {
                            id: item.id,
                            text: item.name
                        }
                    })
                }
            }
        }
    });

    var categories = {!! $book->categories !!}

    categories.forEach(function (category) {
        var option = new Option(category.name, category.id, true, true);
        $('#categories').append(option).trigger('change');
    });

</script>
@endsection

resources/views/books/index.blade.php
@extends('layouts.global')

@section('title') Books list @endsection

@section('content')




<div class="row">
        <div class="col-md-6">
                <form
                action="{{route('books.index')}}"
              >
              
              <div class="input-group">
                  <input name="keyword" type="text" value="{{Request::get('keyword')}}" class="form-control" placeholder="Filter by title">
                  <div class="input-group-append">
                    <input type="submit" value="Filter" class="btn btn-primary">
                  </div>
              </div>
              
              </form>
        </div>
  <div class="col-md-6">
    <ul class="nav nav-pills card-header-pills">
      <li class="nav-item">
        <a class="nav-link {{Request::get('status') == NULL && Request::path() == 'books' ? 'active' : ''}}" href="{{route('books.index')}}">All</a>
      </li>
      <li class="nav-item">
          <a class="nav-link {{Request::get('status') == 'publish' ? 'active' : '' }}" href="{{route('books.index', ['status' => 'publish'])}}">Publish</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {{Request::get('status') == 'draft' ? 'active' : '' }}" href="{{route('books.index', ['status' => 'draft'])}}">Draft</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {{Request::path() == 'books/trash' ? 'active' : ''}}" href="{{route('books.trash')}}">Trash</a>
      </li>
    </ul>
  </div>
</div>
  
  <hr class="my-3">
<div class="row">
    <div class="col-md-12">
            <div class="row mb-3">
                    <div class="col-md-12 text-right">
                        <a href="{{route('books.create')}}" class="btn btn-primary">Create book</a>
                    </div>
                </div>
        <table class="table table-bordered table-stripped">
            <thead>
                <tr>
                    <th><b>Cover</b></th>
                    <th><b>Title</b></th>
                    <th><b>Author</b></th>
                    <th><b>Status</b></th>
                    <th><b>Categories</b></th>
                    <th><b>Stock</b></th>
                    <th><b>Price</b></th>
                    <th><b>Action</b></th>
                </tr>
            </thead>
            <tbody>
                @foreach($books as $book)
                <tr>
                    <td>
                        @if($book->cover)
                        <img src="{{asset('storage/' . $book->cover)}}" width="96px" />
                        @endif
                    </td>
                    <td>{{$book->title}}</td>
                    <td>{{$book->author}}</td>
                    <td>
                        @if($book->status == "DRAFT")
                        <span class="badge bg-dark text-white">{{$book->status}}</span>
                        @else
                        <span class="badge badge-success">{{$book->status}}</span>
                        @endif
                    </td>
                    <td>
                        <ul class="pl-3">
                            @foreach($book->categories as $category)
                            <li>{{$category->name}}</li>
                            @endforeach
                        </ul>
                    </td>
                    <td>{{$book->stock}}</td>
                    <td>{{$book->price}}</td>
                    <td>
                        <a href="{{route('books.edit', ['id' => $book->id])}}" class="btn btn-info btn-sm"> Edit </a>

                        <form method="POST" class="d-inline" onsubmit="return confirm('Move book to trash?')" action="{{route('books.destroy', ['id' => $book->id ])}}">

                            @csrf
                            <input type="hidden" value="DELETE" name="_method">

                            <input type="submit" value="Trash" class="btn btn-danger btn-sm">

                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="10">
                        {{$books->appends(Request::all())->links()}}
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
@endsection

resources/views/books/trash.blade.php
@extends('layouts.global')

@section('title') Trashed Books @endsection

@section('content')

<div class="row">
   
</div>

<div class="row">

    
    <div class="col-md-12">

            <form
            action="{{route('books.index')}}"
          >
          
          
          <div class="input-group">
              <input name="keyword" type="text" value="{{Request::get('keyword')}}" class="form-control" placeholder="Filter by title">
              <div class="input-group-append">
                <input type="submit" value="Filter" class="btn btn-primary">
              </div>
          </div>
          
          </form>
          <br>
        @if(session('status'))
        <div class="alert alert-success">
            {{session('status')}}
        </div>
        @endif

        <table class="table table-bordered table-stripped">
            <thead>
                <tr>
                    <th><b>Cover</b></th>
                    <th><b>Title</b></th>
                    <th><b>Author</b></th>
                    <th><b>Categories</b></th>
                    <th><b>Stock</b></th>
                    <th><b>Price</b></th>
                    <th><b>Action</b></th>
                </tr>
            </thead>
            <tbody>
                @foreach($books as $book)
                <tr>
                    <td>
                        @if($book->cover)
                        <img src="{{asset('storage/' . $book->cover)}}" width="96px" />
                        @endif
                    </td>
                    <td>{{$book->title}}</td>
                    <td>{{$book->author}}</td>
                    <td>
                        <ul class="pl-3">
                            @foreach($book->categories as $category)
                            <li>{{$category->name}}</li>
                            @endforeach
                        </ul>
                    </td>
                    <td>{{$book->stock}}</td>
                    <td>{{$book->price}}</td>
                    <td>
                        <form method="POST" action="{{route('books.restore', ['id' => $book->id])}}" class="d-inline">

                            @csrf

                            <input type="submit" value="Restore" class="btn btn-success btn-sm" />
                        </form>

                        <form method="POST" action="{{route('books.delete-permanent', ['id' => $book->id])}}" class="d-inline"
                            onsubmit="return confirm('Delete this book permanently?')">

                            @csrf
                            <input type="hidden" name="_method" value="DELETE">

                            <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="10">
                        {{$books->appends(Request::all())->links()}}
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
@endsection